services:
  - type: web
    name: driveline-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 photo_enabled_bot_final.py"